[env:esp32]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.filesystem = spiffs
lib_deps =
    me-no-dev/ESPAsyncWebServer @ ^1.2.4
    me-no-dev/AsyncTCP @ ^1.1.1
    bblanchon/ArduinoJson @ ^7.0.0
    Wire
build_flags =
    -DCORE_DEBUG_LEVEL=3
